### ISSUE TITLE
publish a new version to npm?

### ISSUE THREAD

**Issue by dead-horse** [juliangruber/co-read#3]

**Comment by juliangruber** [comment]
just for the cleanup?

**Comment by dead-horse** [comment]
notice it removed generator function, so I can use regenerator to convert my lib(depends on co-read) to support 0.10.x

**Comment by juliangruber** [comment]
i understand. can't regenerator also convert this lib?

**Comment by dead-horse** [comment]
seems like regenerator can not auto detect which file need to be convert.
and also no need to convert every file by regenerator.

**Comment by juliangruber** [comment]
released as 0.0.2

**Comment by dead-horse** [comment]
cool
